---
title: "Music Blog by Alyse L."
date: 2018-08-13
---

title: Music for the Mind
author: Alyse L.
email: myemail@email.com
description: > # this means to ignore newlines until "baseurl:"
  Classical, Jazz, Romantic, Rock... Music has been called an important
  part of child brain development. Explore the effects it has on child
  brain development and more by reading this blog.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
